package h5.concepts.support;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

import org.hibernate.dialect.HSQLDialect;

/**
 * In-memory HSQLDB "HR" schema shared by all the Mains. It is created once per JVM and lives until the
 * JVM exits (no {@code shutdown=true}), so {@link h5.concepts.RunAllMain} reuses it.
 *
 * <pre>
 * DEPARTMENT       PK DEPT_ID (identity), UNIQUE(NAME)
 * EMPLOYEE         PK EMP_ID (filled from sequence EMP_SEQ), FK DEPT_ID -> DEPARTMENT, UNIQUE(EMAIL), VERSION column
 * EMPLOYEE_DETAIL  PK EMP_ID which is also FK -> EMPLOYEE        (=> one-to-one)
 * PROJECT          PK PROJECT_ID
 * EMPLOYEE_PROJECT PK(EMP_ID, PROJECT_ID), both FKs              (=> many-to-many join table)
 * AUDIT_LOG        no PK; excluded from reverse engineering by a TableFilter
 * HIGH_EARNERS     view; skipped by DemoMetaDataDialect.getTables (TABLE only), returned by JDBCMetaDataDialect
 * EMPLOYEE_COUNT(IN dept, OUT count) stored procedure
 * </pre>
 */
public final class DemoDatabase {

    public static final String URL = "jdbc:hsqldb:mem:hr_demo";
    public static final String DRIVER = "org.hsqldb.jdbc.JDBCDriver";
    public static final String USER = "SA";
    public static final String PASSWORD = "";
    public static final String SCHEMA = "PUBLIC";

    private static boolean created;

    private static final String[] DDL = {
        "CREATE SEQUENCE EMP_SEQ START WITH 100",
        "CREATE TABLE DEPARTMENT ("
            + " DEPT_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + " NAME VARCHAR(100) NOT NULL,"
            + " BUDGET DECIMAL(12,2),"
            + " CONSTRAINT UK_DEPT_NAME UNIQUE (NAME))",
        "CREATE TABLE EMPLOYEE ("
            + " EMP_ID INTEGER PRIMARY KEY,"
            + " FIRST_NAME VARCHAR(50) NOT NULL,"
            + " LAST_NAME VARCHAR(50),"
            + " EMAIL VARCHAR(120),"
            + " SALARY DECIMAL(10,2),"
            + " HIRED_ON DATE,"
            + " NOTES CLOB,"
            + " DEPT_ID INTEGER,"
            + " VERSION INTEGER,"
            + " CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID),"
            + " CONSTRAINT UK_EMP_EMAIL UNIQUE (EMAIL))",
        "CREATE TABLE EMPLOYEE_DETAIL ("
            + " EMP_ID INTEGER PRIMARY KEY,"
            + " BIO VARCHAR(1000),"
            + " CONSTRAINT FK_DETAIL_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID))",
        "CREATE TABLE PROJECT ("
            + " PROJECT_ID INTEGER PRIMARY KEY,"
            + " TITLE VARCHAR(100) NOT NULL)",
        "CREATE TABLE EMPLOYEE_PROJECT ("
            + " EMP_ID INTEGER NOT NULL,"
            + " PROJECT_ID INTEGER NOT NULL,"
            + " PRIMARY KEY (EMP_ID, PROJECT_ID),"
            + " CONSTRAINT FK_EP_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),"
            + " CONSTRAINT FK_EP_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID))",
        "CREATE TABLE AUDIT_LOG (MSG VARCHAR(200))",
        "CREATE VIEW HIGH_EARNERS AS SELECT EMP_ID, FIRST_NAME, SALARY FROM EMPLOYEE WHERE SALARY > 9000",
        // Called through a JDBC CallableStatement, like wmstdappdbimpl's procedure tester.
        "CREATE PROCEDURE EMPLOYEE_COUNT(IN P_DEPT_ID INTEGER, OUT P_COUNT INTEGER) READS SQL DATA"
            + " BEGIN ATOMIC SELECT COUNT(*) INTO P_COUNT FROM EMPLOYEE WHERE DEPT_ID = P_DEPT_ID; END",
    };

    private static final String[] DATA = {
        "INSERT INTO DEPARTMENT (NAME, BUDGET) VALUES ('Engineering', 500000.00)",
        "INSERT INTO DEPARTMENT (NAME, BUDGET) VALUES ('Sales', 200000.00)",
        "INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_SEQ, 'Ada', 'Lovelace', 'ada@example.com', 9100.00, DATE '2020-01-15', 'first programmer', 0, 0)",
        "INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_SEQ, 'Alan', 'Turing', 'alan@example.com', 9500.00, DATE '2019-06-01', NULL, 0, 0)",
        "INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_SEQ, 'Grace', 'Hopper', 'grace@example.com', 8700.00, DATE '2021-03-10', NULL, 0, 0)",
        "INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_SEQ, 'Linus', 'Torvalds', 'linus@example.com', 7000.00, DATE '2022-08-20', NULL, 1, 0)",
        "INSERT INTO EMPLOYEE VALUES (NEXT VALUE FOR EMP_SEQ, 'Margaret', 'Hamilton', 'margaret@example.com', 9900.00, DATE '2018-11-05', NULL, 1, 0)",
        "INSERT INTO EMPLOYEE_DETAIL VALUES (100, 'Wrote the first algorithm for a machine.')",
        "INSERT INTO PROJECT VALUES (1, 'Analytical Engine')",
        "INSERT INTO PROJECT VALUES (2, 'Enigma')",
        "INSERT INTO EMPLOYEE_PROJECT VALUES (100, 1)",
        "INSERT INTO EMPLOYEE_PROJECT VALUES (101, 2)",
        "INSERT INTO AUDIT_LOG VALUES ('schema created')",
    };

    private DemoDatabase() {
    }

    /** Creates and seeds the schema the first time it is called; later calls do nothing. */
    public static synchronized void ensureCreated() {
        if (created) {
            return;
        }
        try (Connection connection = openConnection(); Statement statement = connection.createStatement()) {
            for (String sql : DDL) {
                statement.execute(sql);
            }
            for (String sql : DATA) {
                statement.execute(sql);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Could not create demo schema", e);
        }
        created = true;
    }

    public static Connection openConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    /**
     * The {@code hibernate.*} properties for an entity-less SessionFactory, shaped like the ones
     * wmstdappdbimpl's {@code DBConnectionUtils.createConfiguration} sets.
     */
    public static Properties hibernateProperties() {
        Properties props = new Properties();
        props.setProperty("hibernate.dialect", HSQLDialect.class.getName());
        props.setProperty("hibernate.connection.driver_class", DRIVER);
        props.setProperty("hibernate.connection.url", URL);
        props.setProperty("hibernate.connection.username", USER);
        props.setProperty("hibernate.connection.password", PASSWORD);
        props.setProperty("hibernate.show_sql", "false");
        props.setProperty("hibernate.globally_quoted_identifiers", "false");
        props.setProperty("hibernate.hbm2ddl.auto", "none");
        // 5.6: hibernate.temp.use_jdbc_metadata_defaults=false (deprecated alias since 6.5; key renamed).
        props.setProperty("hibernate.boot.allow_jdbc_metadata_access", "false");
        props.setProperty("hibernate.connection.autocommit", "true");
        return props;
    }
}
